#!/usr/bin/env sh

usage() {
	cat <<EOF
Usage: $0 SWALLOWER [-c CLASS] [-i INSTANCE] [-t TITLE]

Queue window SWALLOWER to swallow the next mapped window whose attributes match
the CLASS name, INSTANCE name and window TITLE filters. An empty filters will
match everything.
EOF
}

swallowadd() {
	[ $# -le 1 ] && { usage >&2; exit 1; }

	wid="$1"
	class=
	instance=
	title=
	ii=2
	while [ $ii -le $# ]; do
		eval "arg=\$$ii"
		eval "val=\$$((ii + 1))"
		case "$arg" in
		-c)
			class="$val"
			;;
		-i)
			instance="$val"
			;;
		-t)
			title="$val"
			;;
		*)
			usage >&2
			exit 1
			;;
		esac
		ii=$((ii + 2))
	done

	name="$(printf "${PREFIX}swallowadd${SEP}%u${SEP}%s${SEP}%s${SEP}%s" "$wid" "$class" "$instance" "$title")"
echo "Setting xrootname to:\n\t'$name'\n"
	xsetroot -name "$name"
}

swallowdo() {
	[ ! $# -eq 2 ] && { usage >&2; exit 1; }

	widswer="$1"
	widswee="$2"

	name="$(printf "${PREFIX}swallowdo${SEP}%u${SEP}%u" "$widswer" "$widswee")"
echo "Setting xrootname to:\n\t'$name'\n"
	xsetroot -name "$name"
}

swallowrm() {
	[ ! $# -eq 0 ] && { usage >&2; exit 1; }
	name="$(printf "${PREFIX}swallowrm")"
echo "Setting xrootname to:\n\t'$name'\n"
	xsetroot -name "$name"
}

SEP='###' # As defined in dwm.c:fakesignal()
PREFIX='#!'

case "$1" in
-h|--help)
	usage
	;;
add)
	shift
	swallowadd "$@"
	;;
do)
	shift
	swallowdo "$@"
	;;
rm)
	shift
	swallowrm "$@"
	;;
*)
	usage >&2
	exit 1
	;;
esac