#!/usr/bin/env sh

usage() {
	cat <<EOF
Usage: $0 WINDOW [-c CLASS] [-i INSTANCE] [-t TITLE]

Queue window WINDOW to swallow the next mapped window whose attributes match
the class name, instance name and window title filters.
EOF
}

if [ "$1" = "-h" ] || [ "$1" = "--help" ] || [ $# -eq 0 ]; then
	usage >&2
	exit 1
fi

SEP='###' # As defined in dwm.c:fakesignal()
PREFIX='#!'
wid="$1"
ii=2
while [ $ii -le $# ]; do
	eval "arg=\$$ii"
	eval "val=\$$((ii + 1))"
	case "$arg" in
	-c)
		class="$val"
		;;
	-i)
		instance="$val"
		;;
	-t)
		title="$val"
		;;
	*)
		usage >&2
		exit 1
		;;
	esac
	ii=$((ii + 2))
done

name="$(printf "${PREFIX}swallow${SEP}%u${SEP}%s${SEP}%s${SEP}%s" "$wid" "$class" "$instance" "$title")"
echo "Setting xrootname to:\n\t'$name'\n"
xsetroot -name "$name"